---
title: "Literature Analysis"
author: "Luis Rojo-González"
date: "`r Sys.Date()`"
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
  header-includes:
  - \usepackage{float}
  - \usepackage{amsmath}
  - \usepackage[spanish]{babel}
  - \usepackage[utf8]{inputenc}
  - \usepackage{natbib}
csl: apa.csl
bibliography: Literature.bib
---

```{=tex}
\tableofcontents
\listoffigures
\listoftables
```
```{r echo=FALSE}
#Working directory
setwd("/Users/luisrojo/Library/CloudStorage/OneDrive-usach.cl/PhD/Literature_Review/Coordinated-Charging-Literature-Review")
```

```{r message=FALSE, warning=FALSE}
# libraries
require(readxl)
require(writexl)
require(dplyr)
require(tidyverse)
require(ggplot2)
require(xtable)
require(tikzDevice)
options(mc.cores = parallel::detectCores(),
        # tikzLatex = "PATH",
        tz="CA")
require(caret)
require(MASS)
require(vegan)
```

```{r}
# read the entire date base of articles to read
articles <- read_excel(path = "Database.xlsx", sheet = "ReadingList") %>%
  dplyr::select(c("ID", "Removing phase", "Author Full Names",
                  "Article Title", "Source Title", "Author Keywords",
                  "Keywords Plus", "Publication Year")) %>%
  rename(Author = "Author Full Names", Title = "Article Title",
         Journal = "Source Title", Keywords = "Author Keywords",
         KP = "Keywords Plus", Year = "Publication Year",
         Removing = "Removing phase") %>%
  mutate(Removing = ifelse(is.na(Removing), "Pending", Removing),
         ID = str_replace(ID, pattern = " ", replacement = ""))

# read the filtered papers already read and classified
##### first iteration:
# - single station, 19 articles
# - multi station, 12 articles
# - power grid, 10 articles
classified <- lapply(c("Single_Station", "Multi_Station", "Power_Grid"),
                     function(x) {
                       read_excel(path = "Database.xlsx", sheet = x) %>%
                         mutate(Problem = x)
                       }) %>%
  bind_rows()

data <- left_join(articles %>%
                    mutate(Title = toupper(Title)),
                  classified %>%
                    dplyr::select(-c("Year", "Journal", "Authors", "Abstract",
                                     "Keywords", "Analysis", "Cristicism",
                                     "Why this classification?")) %>%
                    mutate(Title = toupper(Title)),
                  by = "Title")
```

Let's analyze the journal according to the status of the paper read

```{r}
journal_status <- articles %>%
  filter(Removing %in% c("Abstract", "Body", "Pending", "OK")) %>%
  group_by(Removing, Journal) %>%
  summarise(Count = n()) %>%
  ungroup() %>%
  group_by(Journal) %>%
  filter(sum(Count, na.rm = TRUE) != 1) %>%
  ungroup() %>%
  pivot_wider(names_from = Removing, values_from = Count) %>%
  arrange(OK)
```

```{r}
# let's extract the keywords by year, journal and problem
keyword_complete <- apply(data, 1, function(x) {
  # extract keywords
  words <- x["Keywords"] %>%
    # dplyr::select(c("Keywords")) %>%
    # pull() %>%
    strsplit("; ") %>%
    unlist() %>%
    toupper() %>%
    data.frame(Keyword = .)
  
  # assign year, journal and problem
  words <- words %>%
    mutate(ID = x["ID"],
           Year = x["Year"],
           Journal = x["Journal"],
           Problem = x["Problem"],
           Removing = x["Removing"])
  }) %>%
  bind_rows()
```

```{r}
keyword_analysis <- keyword_complete %>%
  filter(Removing %in% c("OK")) %>%
  group_by(Keyword, ID) %>%
  summarise(Count = n()) %>%
  ungroup()
```

```{r}
keyword_id <- keyword_complete %>%
  rowwise() %>%
  mutate(Inclusion = ifelse(Keyword %in% keyword_analysis$Keyword,
                            TRUE, FALSE)) %>%
  ungroup() %>%
  filter(Inclusion) %>%
  dplyr::select(c("ID")) %>%
  pull() %>%
  unique()
```

```{r}
articles_id <- articles %>%
  # in selected journals
  filter(Journal %in% journal_status$Journal) %>%
  # include selected keywords
  filter(ID %in% keyword_id) %>%
  dplyr::select(c("ID")) %>%
  mutate(Inclusion = TRUE)
```

```{r}
articles_final <- left_join(articles,
                            articles_id,
                            by = "ID") %>%
  mutate(Inclusion = ifelse(is.na(Inclusion), FALSE, Inclusion))
```

```{r eval=FALSE, include=FALSE}
# export the results
write.table(x = articles_final %>%
              dplyr::select(c("Inclusion")),
            file = "Deletion.txt",
            row.names = FALSE,
            col.names = FALSE)
```

\section{Data visualization to split the problems}

```{r}
features <- classified %>%
  filter(Selected != "Pending") %>%
  dplyr::select(c("Charging", "V2G", "Battery degradation", "Charging time", "EVs", "EVSE", "Power capacity",
                  "RESs", "Modeling", "Point of view", "Energy market", "Formulation", "Environment",
                  "Dispatching", "Charging facility", "Problem")) %>%
  rename(Battery = `Battery degradation`,
         ChargingTime = `Charging time`,
         PowerCapacity = `Power capacity`,
         PointView = `Point of view`,
         Market = `Energy market`,
         Facility = `Charging facility`) %>%
  rowwise() %>%
  mutate(EVs = strsplit(EVs," ")[[1]][1],
         EVSE = strsplit(EVSE," ")[[1]][1]) %>%
  ungroup() %>%
  mutate(ChargingTime = ifelse(ChargingTime %in% c("Linear", "Nonlinear"), ChargingTime, "Linear"),
         PowerCapacity = ifelse(PowerCapacity == "No", PowerCapacity, "Yes"),
         RESs = ifelse(RESs == "No", RESs, "Yes"),
         PointView = ifelse(PointView == "AU", PointView, "Driver")) %>%
  separate(col = Formulation, into = c("PowerSupply", "Preemptive"), sep = " ") %>%
  mutate(Preemptive = ifelse(str_replace(Preemptive, ",", "") == "(Preemptive)", "Yes", "No")) %>%
  separate(col = Environment, into = c("Aux1", "Aux2"), sep = " and ") %>%
  separate(col = Aux1, into = c("Method1", "Model1"), sep = " ") %>%
  separate(col = Aux2, into = c("Method2", "Model2"), sep = " ") %>%
  mutate(Model1 = str_extract(Model1, "(?<=\\().*(?=\\))"),
         Model2 = str_extract(Model2, "(?<=\\().*(?=\\))")) %>%
  filter(Method1 == "Optimization" | Method2 == "Optimization") %>%
  dplyr::select(-c(Model1, Model2, Method1, Method2)) %>%
  separate(Facility, into = c("Facility", "FacilityType"), sep = " ") %>%
  mutate(FacilityType = str_extract(FacilityType, "(?<=\\().*(?=\\))")) %>%
  na.omit()
```

\subsection{Distance metric: Jaccard index}

```{r}
df_features_factor <- as.data.frame(apply(features, 2, function(x) as.factor(x)), stringsAsFactors = TRUE)

dummy <- dummyVars(" ~ .", data = df_features_factor)
df_binary <- data.frame(predict(dummy, newdata = df_features_factor))
```

```{r}
# set the jaccard distance function
jaccard_distance <- function(a, b) {
  n_ones <- sum(a == 1 & b == 1)
  n_zero_one <- sum(a == 0 & b == 1)
  n_one_zero <- sum(a == 1 & b == 0)

  distance <- n_ones / (n_ones + n_zero_one + n_one_zero)
  return(1 - distance)
}
```

```{r}
jaccard_matrix <- matrix(nrow = nrow(df_binary), ncol = nrow(df_binary))
for(i in 1:nrow(df_binary)) {
  for(j in 1:nrow(df_binary)) {
    jaccard_matrix[i, j] <- jaccard_distance(df_binary[i, ],
                                             df_binary[j, ])
  }
}
```

\subsection{Multidimensional scalling}

```{r}
# Multi-Dimensional scaling
set.seed(12345)

mds_jaccard = metaMDS(comm = jaccard_matrix,
                      # distance = "jaccard",
                      binary = TRUE,
                      k = 2, # number of dimensions to project
                      try = floor(0.1*nrow(jaccard_matrix)),
                      trymax = floor(0.5*nrow(jaccard_matrix)),
                      engine = "monoMDS",
                      stress = 1,
                      autotransform = FALSE,
                      wascores = FALSE,
                      maxit = 1000,
                      zerodist = "add")
```

```{r}
# get the solution from the MDS
mds_points = mds_jaccard$points %>%
  as_tibble() %>%
  rename(x = MDS1, y = MDS2) %>%
  add_column(., Problem = df_features_factor$Problem)

# mds_species = mds_jaccard$species %>%
#   as_tibble() %>%
#   rename(x = MDS1, y = MDS2, z = MDS3)
```


```{r}
# plot the results
ggplot() +
  geom_vline(xintercept = 0,
             linetype = "dashed") +
  geom_hline(yintercept = 0,
             linetype = "dashed") +
  geom_point(data = mds_points,
             aes(x, y,
                 colour = Problem),
             alpha = 1) +
  # # add the country names
  # geom_text(data = mds_points,
  #           aes(x, y,
  #               label = data[, 1] %>% pull()),
  #           size = 2.5,
  #           parse = FALSE,
  #           vjust = "outward",
  #           hjust = "outward",
  #           # family = "Times",
  #           col = "black") +
  # geom_text(data = mds_species,
  #           aes(x, y,
  #               label = rownames(mds_bray$species)),
  #           size = 3.5,
  #           parse = TRUE,
  #           vjust = "outward",
  #           hjust = "outward",
  #           # family = "Times",
  #           col = "black") +
  # geom_segment(data = mds_species,
  #              aes(x = 0,
  #                  xend = x,
  #                  y = 0,
  #                  yend = y),
  #              size = 1,
  #              arrow = arrow(length = unit(0.1, "in")),
  #              col = "red") +
  theme_classic() +
  theme(legend.position = "bottom",
        panel.border = element_rect(fill = NA, colour = "black")) +
  guides(colour = guide_legend(override.aes = list(size = 2.5)),
         shape = guide_legend(override.aes = list(size = 2.5))) +
  labs(x = "NMDS1",
       y = "NMDS1",
       colour = "Problem",
       title = paste("Kruskal's stress:",
                     round(mds_jaccard[["stress"]], 2), "%")) +
  coord_fixed()
```


